"""
Global system constants for the Sales Intelligence Backend.
"""

# API Standard Status Codes
STATUS_SUCCESS = "SUCCESS"
STATUS_ERROR = "ERROR"
STATUS_VALIDATION_ERROR = "VALIDATION_ERROR"
STATUS_UNAUTHORIZED = "UNAUTHORIZED"
STATUS_FORBIDDEN = "FORBIDDEN"
STATUS_NOT_FOUND = "NOT_FOUND"

# Signal Status Choices
SIGNAL_STATUS_NEW = "NEW"
SIGNAL_STATUS_PROCESSED = "PROCESSED"
SIGNAL_STATUS_ARCHIVED = "ARCHIVED"

SIGNAL_STATUSES = (
    (SIGNAL_STATUS_NEW, "New"),
    (SIGNAL_STATUS_PROCESSED, "Processed"),
    (SIGNAL_STATUS_ARCHIVED, "Archived"),
)

# Deal Stage Choices
DEAL_STAGE_PROSPECTING = "PROSPECTING"
DEAL_STAGE_QUALIFICATION = "QUALIFICATION"
DEAL_STAGE_PROPOSAL = "PROPOSAL"
DEAL_STAGE_NEGOTIATION = "NEGOTIATION"
DEAL_STAGE_CLOSED_WON = "CLOSED_WON"
DEAL_STAGE_CLOSED_LOST = "CLOSED_LOST"

DEAL_STAGES = (
    (DEAL_STAGE_PROSPECTING, "Prospecting"),
    (DEAL_STAGE_QUALIFICATION, "Qualification"),
    (DEAL_STAGE_PROPOSAL, "Proposal"),
    (DEAL_STAGE_NEGOTIATION, "Negotiation"),
    (DEAL_STAGE_CLOSED_WON, "Closed Won"),
    (DEAL_STAGE_CLOSED_LOST, "Closed Lost"),
)

# Pagination Defaults
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100
